version: '3.3'
services:
  webdriver:
    restart: unless-stopped
    ports:
      - '4444:4444'
      # uncomment for live browser view
      - '7900:7900'
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--silent",
          "--fail",
          "http://localhost:4444"
        ]
      interval: 2s
      timeout: 60s
    image: 'selenium/standalone-firefox:4.8.1-20230306'
  scraper:
    restart: unless-stopped
    build: ./scraper
    env_file:
      - secrets.env
    volumes:
      - ./scraper:/usr/src/app
      - ./podcasts:/podcasts
    depends_on:
      webdriver:
        condition: service_healthy
